version: '3.1'

services:
  db:
    image: mysql
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B',
        ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 3308:3306
